portfolio/views/general.py
from flask import Blueprint
from flask import render_template

from portfolio.models import Category

bp = Blueprint('general', __name__)


def get_categories():
    return Category.query.all()


@bp.route('/')
def index():
    return render_template('general/index.html')


@bp.route('/gallery/<category_name_url>')
def gallery(category_name_url: str):
    category = Category.query.filter_by(name_url=category_name_url).first()
    return render_template('general/index.html', pictures=category.pictures)


@bp.route('/contact')
def contact():
    return render_template('general/contact.html')

portfolio/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>{% block title %}{% endblock %} - Portfolio</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body>
        <nav>
            <h1>Portfolio</h1>
        </nav>
        <section class="content">
            <header>
                {% block header %}{% endblock%} 
            </header>
            {% for message  in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
            {% endfor %}
            {% block content %}{% endblock %}
        </section>
    </body>
</html>

portfolio/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>{% block title %}{% endblock %} - Portfolio</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body>
        <nav>
            <h1>Portfolio</h1>
        </nav>
        <section class="content">
            <header>
                {% block header %}{% endblock%} 
                <nav>
                    <ul>
                        <li><a href="/">Home</a></li>
                        {% for category in get_categories() %}
                        {% if not category.hidden %}
                        <li><a href="{{ url_for('general.gallery', category_name_url=category.name_url) }}">{{ category.name }}</a></li>
                        {% endif %}
                        {% endfor %}
                        <li><a href="{{ url_for('general.contact') }}">Contact</a></li>
                        {% if g.user %}
                        <li><a href="{{ url_for('admin.index') }}">Admin</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </header>
            {% for message  in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
            {% endfor %}
            {% block content %}{% endblock %}
        </section>
    </body>
</html>